version: '3.3'
services:
  node:
    image: node:16-bullseye
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npm run start:dev"
    ports:
      - 3001:3000
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme} # password (or 'changeme')
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
volumes:
  postgres:
  pgadmin:
